3.DATASET
The dataset for this paper has been obtained 
from the UCI Machine Learning Repository (https://archive.ics.uci.edu/ml/datasets/Automobile).

This data set consists of three types of entities: (a) the specification of an auto in terms of various 
characteristics, (b)its assigned insurance risk rating, (c) its normalized losses in use as compared to other cars.

The second rating corresponds to the degree to which the auto is more risky than its price indicates.
Cars are initially assigned a risk factor symbol associated with its price. Then, if it is more risky 
(or less), this symbol is adjusted by moving it up (or down) the scale. Actuarians call this process 
“symboling”. A value of +3 indicates that the auto is risky, -3 that it is probably pretty safe.

The third factor is the relative average loss payment per insured vehicle year. This value is normalized 
for all autos within a particular size classification (two-door small, station wagons, sports/speciality, etc…),
and represents the average loss per car per year.

There are total 205 instances and 26 attributes out of which 15 are continuous, 1 is integer and 
10 are nominal. There are missing values as well.

## USING THE BRAND (MAKE) INFORMATION TO FILL THE MISSING VALUES
WE USE A SIMILAR CAR FROM THE SAME BRAND (MAKE) TO FILL THE MISSING VALUE

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

# to display the total number columns present in the dataset
pd.set_option('display.max_columns', None)

In [2]:
# let's load the imports-85 automobile dataset
header_list = ['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 
               'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 
               'length', 'width','height', 'curb-weight', 'engine-type', 'num-of-cylinders',
               'engine-size', 'fuel-system','bore', 'stroke', 'compression-ratio', 
               'horsepower', 'peak-rpm','city-mpg', 'highway-mpg', 'price']
data = pd.read_csv('C:\\Users\\gusal\\machine learning\\Feature engineering\\automobile data set\\imports-85 - data.txt', names = header_list)


In [3]:
# let's inspect the first 5 rows
data.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  length  width  \
0  convertible          rwd           front        88.6   168.8   64.1   
1  convertible          rwd           front        88.6   168.8   64.1   
2    hatchback          rwd           front        94.5   171.2   65.5   
3        sedan          fwd           front        99.8   176.6   66.2   
4        sedan          4wd           front        99.4   176.6   66.4   

   height  curb-weight engine-type num-of-cylinders  engine-size fuel-system  \
0    48.8         2548        dohc             four          130        mpfi   
1    48.8         2548        dohc             four          130        mpfi   
2    52.4         2823        ohcv              six          152        mpfi   
3    54.3         2337         ohc             four          109        mpfi   
4    54.3         2824         ohc             five          136        mpfi   

   bore stroke  compression-ratio horsepower peak-rpm  city-mpg  highway-mpg  \
0  3.47   2.68                9.0        111     5000        21           27   
1  3.47   2.68                9.0        111     5000        21           27   
2  2.68   3.47                9.0        154     5000        19           26   
3  3.19   3.40               10.0        102     5500        24           30   
4  3.19   3.40                8.0        115     5500        18           22   

   price  
0  13495  
1  16500  
2  16500  
3  13950  
4  17450

In [4]:
data = data.replace('?', np.nan)

In [5]:
data.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3               NaN  alfa-romero       gas        std          two   
1          3               NaN  alfa-romero       gas        std          two   
2          1               NaN  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  length  width  \
0  convertible          rwd           front        88.6   168.8   64.1   
1  convertible          rwd           front        88.6   168.8   64.1   
2    hatchback          rwd           front        94.5   171.2   65.5   
3        sedan          fwd           front        99.8   176.6   66.2   
4        sedan          4wd           front        99.4   176.6   66.4   

   height  curb-weight engine-type num-of-cylinders  engine-size fuel-system  \
0    48.8         2548        dohc             four          130        mpfi   
1    48.8         2548        dohc             four          130        mpfi   
2    52.4         2823        ohcv              six          152        mpfi   
3    54.3         2337         ohc             four          109        mpfi   
4    54.3         2824         ohc             five          136        mpfi   

   bore stroke  compression-ratio horsepower peak-rpm  city-mpg  highway-mpg  \
0  3.47   2.68                9.0        111     5000        21           27   
1  3.47   2.68                9.0        111     5000        21           27   
2  2.68   3.47                9.0        154     5000        19           26   
3  3.19   3.40               10.0        102     5500        24           30   
4  3.19   3.40                8.0        115     5500        18           22   

   price  
0  13495  
1  16500  
2  16500  
3  13950  
4  17450

In [6]:
data.to_csv('C:\\Users\\gusal\\machine learning\\Feature engineering\\automobile data set\\imports-85 - data.csv')

In [7]:
data_raw = data.copy()

In [8]:
data_raw.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [9]:
# we can quantify the total number of missing values using
# the isnull method plus the sum method on the dataframe

data_raw.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

There are: 41 missing values for normalized-losses, 2 for num-of-doors, 4 for bore, 
4 for stroke, 2 for horsepower, 2 for peak-rpm and 4 for price.
    

In [10]:
# alternatively, we can use the mean method after isnull
# to visualise the percentage of
# missing values for each variable

vars_with_na = [var for var in data_raw.columns if data_raw[var].isnull().mean() > 0]

# percentage of missing values for each variable

data_na = data_raw[vars_with_na].isnull().mean()
data_na = pd.DataFrame(data_na.reset_index())

#adding columns to the dataframe
data_na.columns = ['Features', 'na_percentage_*100']
data_na['na_percentage_*100']= data_na['na_percentage_*100']*100

data_na.sort_values(by = 'na_percentage_*100', ascending = False, inplace = True)

In [11]:
data_na

Features  na_percentage_*100
0  normalized-losses            20.00000
2               bore             1.95122
3             stroke             1.95122
6              price             1.95122
1       num-of-doors             0.97561
4         horsepower             0.97561
5           peak-rpm             0.97561

There are: 20% missing values for normalized-losses, 1% for num-of-doors, 2% for bore, 
2% for stroke, 1% for horsepower, 1% for peak-rpm and 2% for price.

TRANSFORMING TYPE OF DATA TO FLOAT IN ORDER TO FIND THE MEAN AND THE MEDIAN 

In [12]:
data_raw['normalized-losses'] = data_raw['normalized-losses'].astype(float)

In [13]:
data_raw['bore'] = data_raw['bore'].astype(float)

In [14]:
data_raw['stroke'] = data_raw['stroke'].astype(float)

In [15]:
data_raw['horsepower'] = data_raw['horsepower'].astype(float)

In [16]:
data_raw['peak-rpm'] = data_raw['peak-rpm'].astype(float)

In [17]:
data_raw['price'] = data_raw['price'].astype(float)

In [18]:
# adding columns with the missing values to the dataframe data_raw

# First we create a binary variable to indicates
# whether the value of normalized-losses is missing

data_raw['normalized-losses_null'] = np.where(data_raw['normalized-losses'].isnull(), 1, 0)
data_raw['num-of-doors_null'] = np.where(data_raw['num-of-doors'].isnull(), 1, 0)
data_raw['bore_null'] = np.where(data_raw['bore'].isnull(), 1, 0)
data_raw['stroke_null'] = np.where(data_raw['stroke'].isnull(), 1, 0)
data_raw['horsepower_null'] = np.where(data_raw['horsepower'].isnull(), 1, 0)
data_raw['peak-rpm_null'] = np.where(data_raw['peak-rpm'].isnull(), 1, 0)
data_raw['price_null'] = np.where(data_raw['price'].isnull(), 1, 0)

In [19]:
data_raw.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std   
1          3                NaN  alfa-romero       gas        std   
2          1                NaN  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  length  \
0          two  convertible          rwd           front        88.6   168.8   
1          two  convertible          rwd           front        88.6   168.8   
2          two    hatchback          rwd           front        94.5   171.2   
3         four        sedan          fwd           front        99.8   176.6   
4         four        sedan          4wd           front        99.4   176.6   

   width  height  curb-weight engine-type num-of-cylinders  engine-size  \
0   64.1    48.8         2548        dohc             four          130   
1   64.1    48.8         2548        dohc             four          130   
2   65.5    52.4         2823        ohcv              six          152   
3   66.2    54.3         2337         ohc             four          109   
4   66.4    54.3         2824         ohc             five          136   

  fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
0        mpfi  3.47    2.68                9.0       111.0    5000.0   
1        mpfi  3.47    2.68                9.0       111.0    5000.0   
2        mpfi  2.68    3.47                9.0       154.0    5000.0   
3        mpfi  3.19    3.40               10.0       102.0    5500.0   
4        mpfi  3.19    3.40                8.0       115.0    5500.0   

   city-mpg  highway-mpg    price  normalized-losses_null  num-of-doors_null  \
0        21           27  13495.0                       1                  0   
1        21           27  16500.0                       1                  0   
2        19           26  16500.0                       1                  0   
3        24           30  13950.0                       0                  0   
4        18           22  17450.0                       0                  0   

   bore_null  stroke_null  horsepower_null  peak-rpm_null  price_null  
0          0            0                0              0           0  
1          0            0                0              0           0  
2          0            0                0              0           0  
3          0            0                0              0           0  
4          0            0                0              0           0

In [20]:
# making a groups of make
h = data_raw.make.value_counts()

In [21]:
# making a table based in the groups of make 
df1 = pd.DataFrame(h)

In [22]:
# grouping around 'make', to find if there are missing data related to each make:
a = data_raw.groupby(['make'])['normalized-losses_null'].sum()
b = data_raw.groupby(['make'])['num-of-doors_null'].sum()
c = data_raw.groupby(['make'])['bore_null'].sum()
d = data_raw.groupby(['make'])['stroke_null'].sum()
e = data_raw.groupby(['make'])['horsepower_null'].sum()
f = data_raw.groupby(['make'])['peak-rpm_null'].sum()
g = data_raw.groupby(['make'])['price_null'].sum()

In [23]:
df1['normalized-losses_null'] = a
df1['num-of-doors_null'] = b
df1['bore_null'] = c
df1['stroke_null'] = d
df1['horsepower_null'] = e
df1['peak-rpm_null'] = f
df1['price_null'] = g

In [24]:
#MISSING VALUES PER MAKE (BRAND)
df1

make  normalized-losses_null  num-of-doors_null  bore_null  \
toyota           32                       1                  0          0   
nissan           18                       0                  0          0   
mazda            17                       2                  1          4   
mitsubishi       13                       3                  0          0   
honda            13                       0                  0          0   
subaru           12                       0                  0          0   
volkswagen       12                       4                  0          0   
peugot           11                       4                  0          0   
volvo            11                       0                  0          0   
dodge             9                       0                  1          0   
mercedes-benz     8                       3                  0          0   
bmw               8                       4                  0          0   
audi              7                       3                  0          0   
plymouth          7                       1                  0          0   
saab              6                       0                  0          0   
porsche           5                       4                  0          0   
isuzu             4                       4                  0          0   
jaguar            3                       2                  0          0   
chevrolet         3                       0                  0          0   
alfa-romero       3                       3                  0          0   
renault           2                       2                  0          0   
mercury           1                       1                  0          0   

               stroke_null  horsepower_null  peak-rpm_null  price_null  
toyota                   0                0              0           0  
nissan                   0                0              0           0  
mazda                    4                0              0           0  
mitsubishi               0                0              0           0  
honda                    0                0              0           0  
subaru                   0                0              0           0  
volkswagen               0                0              0           0  
peugot                   0                0              0           0  
volvo                    0                0              0           0  
dodge                    0                0              0           0  
mercedes-benz            0                0              0           0  
bmw                      0                0              0           0  
audi                     0                0              0           1  
plymouth                 0                0              0           0  
saab                     0                0              0           0  
porsche                  0                0              0           1  
isuzu                    0                0              0           2  
jaguar                   0                0              0           0  
chevrolet                0                0              0           0  
alfa-romero              0                0              0           0  
renault                  0                2              2           0  
mercury                  0                0              0           0

## Missing at Random, MAR
all the automobiles from alfa-romero, isuzu, renault and mercury have missing information for normalized-losses.
In this case it can be considered Missing at Random (MAR).


## Missing data Completely At Random (MCAR)
A priori, there does not seem to be an indication that the missing information for all the variables, except normalized-losses, is depending on any other variable
the missing values in num-of-doors, bore, stroke, horsepower, peak-rpm and price are considered MCAR.

## WE USE THE BRAND (MAKE) INFORMATION TO FILL THE MISSING VALUES

FIRST, WE MAKE A TABLE FOR EACH BRAND WITH MISSING VALUES. NOW WE FIND SIMILAR AUTOMOBILES TO THE ONES WITH MISSING VALUES.

In [25]:
df10 = data_raw.loc[data_raw['make'] == 'toyota']
df10

symboling  normalized-losses    make fuel-type aspiration num-of-doors  \
150          1               87.0  toyota       gas        std          two   
151          1               87.0  toyota       gas        std          two   
152          1               74.0  toyota       gas        std         four   
153          0               77.0  toyota       gas        std         four   
154          0               81.0  toyota       gas        std         four   
155          0               91.0  toyota       gas        std         four   
156          0               91.0  toyota       gas        std         four   
157          0               91.0  toyota       gas        std         four   
158          0               91.0  toyota    diesel        std         four   
159          0               91.0  toyota    diesel        std         four   
160          0               91.0  toyota       gas        std         four   
161          0               91.0  toyota       gas        std         four   
162          0               91.0  toyota       gas        std         four   
163          1              168.0  toyota       gas        std          two   
164          1              168.0  toyota       gas        std          two   
165          1              168.0  toyota       gas        std          two   
166          1              168.0  toyota       gas        std          two   
167          2              134.0  toyota       gas        std          two   
168          2              134.0  toyota       gas        std          two   
169          2              134.0  toyota       gas        std          two   
170          2              134.0  toyota       gas        std          two   
171          2              134.0  toyota       gas        std          two   
172          2              134.0  toyota       gas        std          two   
173         -1               65.0  toyota       gas        std         four   
174         -1               65.0  toyota    diesel      turbo         four   
175         -1               65.0  toyota       gas        std         four   
176         -1               65.0  toyota       gas        std         four   
177         -1               65.0  toyota       gas        std         four   
178          3              197.0  toyota       gas        std          two   
179          3              197.0  toyota       gas        std          two   
180         -1               90.0  toyota       gas        std         four   
181         -1                NaN  toyota       gas        std         four   

      body-style drive-wheels engine-location  wheel-base  length  width  \
150    hatchback          fwd           front        95.7   158.7   63.6   
151    hatchback          fwd           front        95.7   158.7   63.6   
152    hatchback          fwd           front        95.7   158.7   63.6   
153        wagon          fwd           front        95.7   169.7   63.6   
154        wagon          4wd           front        95.7   169.7   63.6   
155        wagon          4wd           front        95.7   169.7   63.6   
156        sedan          fwd           front        95.7   166.3   64.4   
157    hatchback          fwd           front        95.7   166.3   64.4   
158        sedan          fwd           front        95.7   166.3   64.4   
159    hatchback          fwd           front        95.7   166.3   64.4   
160        sedan          fwd           front        95.7   166.3   64.4   
161    hatchback          fwd           front        95.7   166.3   64.4   
162        sedan          fwd           front        95.7   166.3   64.4   
163        sedan          rwd           front        94.5   168.7   64.0   
164    hatchback          rwd           front        94.5   168.7   64.0   
165        sedan          rwd           front        94.5   168.7   64.0   
166    hatchback          rwd           front        94.5   168.7   64.0   
167      hardtop          rwd

CHECK MISSING VALUES FOR MAKE toyota

the car with index number 180 is almost identical to index car 181. therfore we assume they have the same normalized losses

In [26]:
#df.at[0,’Age']= 20
data_raw.iloc[181,1]= data_raw.iloc[180,1]

CHECK MISSING VALUES FOR MAKE mazda

In [27]:
df11 = data_raw.loc[data_raw['make'] == 'mazda']
df11

symboling  normalized-losses   make fuel-type aspiration num-of-doors  \
50          1              104.0  mazda       gas        std          two   
51          1              104.0  mazda       gas        std          two   
52          1              104.0  mazda       gas        std          two   
53          1              113.0  mazda       gas        std         four   
54          1              113.0  mazda       gas        std         four   
55          3              150.0  mazda       gas        std          two   
56          3              150.0  mazda       gas        std          two   
57          3              150.0  mazda       gas        std          two   
58          3              150.0  mazda       gas        std          two   
59          1              129.0  mazda       gas        std          two   
60          0              115.0  mazda       gas        std         four   
61          1              129.0  mazda       gas        std          two   
62          0              115.0  mazda       gas        std         four   
63          0                NaN  mazda    diesel        std          NaN   
64          0              115.0  mazda       gas        std         four   
65          0              118.0  mazda       gas        std         four   
66          0                NaN  mazda    diesel        std         four   

   body-style drive-wheels engine-location  wheel-base  length  width  height  \
50  hatchback          fwd           front        93.1   159.1   64.2    54.1   
51  hatchback          fwd           front        93.1   159.1   64.2    54.1   
52  hatchback          fwd           front        93.1   159.1   64.2    54.1   
53      sedan          fwd           front        93.1   166.8   64.2    54.1   
54      sedan          fwd           front        93.1   166.8   64.2    54.1   
55  hatchback          rwd           front        95.3   169.0   65.7    49.6   
56  hatchback          rwd           front        95.3   169.0   65.7    49.6   
57  hatchback          rwd           front        95.3   169.0   65.7    49.6   
58  hatchback          rwd           front        95.3   169.0   65.7    49.6   
59  hatchback          fwd           front        98.8   177.8   66.5    53.7   
60      sedan          fwd           front        98.8   177.8   66.5    55.5   
61  hatchback          fwd           front        98.8   177.8   66.5    53.7   
62      sedan          fwd           front        98.8   177.8   66.5    55.5   
63      sedan          fwd           front        98.8   177.8   66.5    55.5   
64  hatchback          fwd           front        98.8   177.8   66.5    55.5   
65      sedan          rwd           front       104.9   175.0   66.1    54.4   
66      sedan          rwd           front       104.9   175.0   66.1    54.4   

    curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  \
50         1890         ohc             four           91        2bbl  3.03   
51         1900         ohc             four           91        2bbl  3.03   
52         1905         ohc             four           91        2bbl  3.03   
53         1945         ohc             four           91        2bbl  3.03   
54         1950         ohc             four           91        2bbl  3.08   
55         2380       rotor              two           70        4bbl   NaN   
56         2380       rotor              two           70        4bbl   NaN   
57         2385       rotor              two           70        4bbl   NaN   
58         2500       rotor              two           80        mpfi   NaN   
59         2385         ohc             four          122        2bbl  3.39   
60         2410         ohc             four          122        2bbl  3.39   
61         2385         ohc             four          122        2bbl  3.39   
62         2410         ohc             four          122        2bbl  3.39   
63         2443         ohc             four        

the car with index number 63 is almost identical to index car 62. therfore we assume they have the same normalized loss,
number of doors and fuel system

In [28]:
data_raw.iloc[63,1]= data_raw.iloc[62,1]
data_raw.iloc[63,5]= data_raw.iloc[62,5]
#data_raw.iloc[63,17]= data_raw.iloc[62,17]

the car with index number 66 is similar to index car 65 and 64. therfore we assume they have the same normalized loss and fuel system

In [29]:
data_raw.iloc[66,1]= data_raw.iloc[65,1]
#data_raw.iloc[66,17]= data_raw.iloc[64,17]
#data_raw.iloc[65,17]= data_raw.iloc[64,17]

for bore and stroke in index cars 55 to 58, we assign the same values of index car 54

In [30]:
data_raw.iloc[55,18]= data_raw.iloc[54,18]
data_raw.iloc[55,19]= data_raw.iloc[54,19]
data_raw.iloc[56,18]= data_raw.iloc[54,18]
data_raw.iloc[56,19]= data_raw.iloc[54,19]
data_raw.iloc[57,18]= data_raw.iloc[54,18]
data_raw.iloc[57,19]= data_raw.iloc[54,19]
data_raw.iloc[58,18]= data_raw.iloc[54,18]
data_raw.iloc[58,19]= data_raw.iloc[54,19]

In [31]:
#CHECK MISSING VALUES FOR MAKE dogde

df12 = data_raw.loc[data_raw['make'] == 'dodge']
df12

symboling  normalized-losses   make fuel-type aspiration num-of-doors  \
21          1              118.0  dodge       gas        std          two   
22          1              118.0  dodge       gas        std          two   
23          1              118.0  dodge       gas      turbo          two   
24          1              148.0  dodge       gas        std         four   
25          1              148.0  dodge       gas        std         four   
26          1              148.0  dodge       gas        std         four   
27          1              148.0  dodge       gas      turbo          NaN   
28         -1              110.0  dodge       gas        std         four   
29          3              145.0  dodge       gas      turbo          two   

   body-style drive-wheels engine-location  wheel-base  length  width  height  \
21  hatchback          fwd           front        93.7   157.3   63.8    50.8   
22  hatchback          fwd           front        93.7   157.3   63.8    50.8   
23  hatchback          fwd           front        93.7   157.3   63.8    50.8   
24  hatchback          fwd           front        93.7   157.3   63.8    50.6   
25      sedan          fwd           front        93.7   157.3   63.8    50.6   
26      sedan          fwd           front        93.7   157.3   63.8    50.6   
27      sedan          fwd           front        93.7   157.3   63.8    50.6   
28      wagon          fwd           front       103.3   174.6   64.6    59.8   
29  hatchback          fwd           front        95.9   173.2   66.3    50.2   

    curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  \
21         1876         ohc             four           90        2bbl  2.97   
22         1876         ohc             four           90        2bbl  2.97   
23         2128         ohc             four           98        mpfi  3.03   
24         1967         ohc             four           90        2bbl  2.97   
25         1989         ohc             four           90        2bbl  2.97   
26         1989         ohc             four           90        2bbl  2.97   
27         2191         ohc             four           98        mpfi  3.03   
28         2535         ohc             four          122        2bbl  3.34   
29         2811         ohc             four          156         mfi  3.60   

    stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg  \
21    3.23               9.41        68.0    5500.0        37           41   
22    3.23               9.40        68.0    5500.0        31           38   
23    3.39               7.60       102.0    5500.0        24           30   
24    3.23               9.40        68.0    5500.0        31           38   
25    3.23               9.40        68.0    5500.0        31           38   
26    3.23               9.40        68.0    5500.0        31           38   
27    3.39               7.60       102.0    5500.0        24           30   
28    3.46               8.50        88.0    5000.0        24           30   
29    3.90               7.00       145.0    5000.0        19           24   

      price  normalized-losses_null  num-of-doors_null  bore_null  \
21   5572.0                       0                  0          0   
22   6377.0                       0                  0          0   
23   7957.0                       0                  0          0   
24   6229.0                       0                  0          0   
25   6692.0                       0                  0          0   
26   7609.0                       0                  0          0   
27   8558.0                       0                  1          0   
28   8921.0                       0                  0          0   
29  12964.0                       0                  0          0   

    stroke_null  horsepower_null  peak-rpm_null  price_null  
21            0                0              0           0  
22            0                0   

the car with index number 26 is similar to index car 27. therfore we assume they have the same number of doors

In [32]:
data_raw.iloc[27,5]= data_raw.iloc[26,5]

In [33]:
#CHECK MISSING VALUES FOR MAKE mitsubishi

df13 = data_raw.loc[data_raw['make'] == 'mitsubishi']
df13

symboling  normalized-losses        make fuel-type aspiration  \
76          2              161.0  mitsubishi       gas        std   
77          2              161.0  mitsubishi       gas        std   
78          2              161.0  mitsubishi       gas        std   
79          1              161.0  mitsubishi       gas      turbo   
80          3              153.0  mitsubishi       gas      turbo   
81          3              153.0  mitsubishi       gas        std   
82          3                NaN  mitsubishi       gas      turbo   
83          3                NaN  mitsubishi       gas      turbo   
84          3                NaN  mitsubishi       gas      turbo   
85          1              125.0  mitsubishi       gas        std   
86          1              125.0  mitsubishi       gas        std   
87          1              125.0  mitsubishi       gas      turbo   
88         -1              137.0  mitsubishi       gas        std   

   num-of-doors body-style drive-wheels engine-location  wheel-base  length  \
76          two  hatchback          fwd           front        93.7   157.3   
77          two  hatchback          fwd           front        93.7   157.3   
78          two  hatchback          fwd           front        93.7   157.3   
79          two  hatchback          fwd           front        93.0   157.3   
80          two  hatchback          fwd           front        96.3   173.0   
81          two  hatchback          fwd           front        96.3   173.0   
82          two  hatchback          fwd           front        95.9   173.2   
83          two  hatchback          fwd           front        95.9   173.2   
84          two  hatchback          fwd           front        95.9   173.2   
85         four      sedan          fwd           front        96.3   172.4   
86         four      sedan          fwd           front        96.3   172.4   
87         four      sedan          fwd           front        96.3   172.4   
88         four      sedan          fwd           front        96.3   172.4   

    width  height  curb-weight engine-type num-of-cylinders  engine-size  \
76   64.4    50.8         1918         ohc             four           92   
77   64.4    50.8         1944         ohc             four           92   
78   64.4    50.8         2004         ohc             four           92   
79   63.8    50.8         2145         ohc             four           98   
80   65.4    49.4         2370         ohc             four          110   
81   65.4    49.4         2328         ohc             four          122   
82   66.3    50.2         2833         ohc             four          156   
83   66.3    50.2         2921         ohc             four          156   
84   66.3    50.2         2926         ohc             four          156   
85   65.4    51.6         2365         ohc             four          122   
86   65.4    51.6         2405         ohc             four          122   
87   65.4    51.6         2403         ohc             four          110   
88   65.4    51.6         2403         ohc             four          110   

   fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
76        2bbl  2.97    3.23                9.4        68.0    5500.0   
77        2bbl  2.97    3.23                9.4        68.0    5500.0   
78        2bbl  2.97    3.23                9.4        68.0    5500.0   
79        spdi  3.03    3.39                7.6       102.0    5500.0   
80        spdi  3.17    3.46                7.5       116.0    5500.0   
81        2bbl  3.35    3.46                8.5        88.0    5000.0   
82        spdi  3.58    3.86                7.0       145.0    5000.0   
83        spdi  3.59    3.86                7.0       145.0    5000.0   
84        spdi  3.59    3.86                7.0       145.0    5000.0   
85        2bbl  3.35    3.46                8.5        88.0    5000.0   
86        2bbl  3.35    3.46                8.5        88.0   

the car with index number 81 is similar to index car 82, 83 and 84. 
therfore we assume they have the same normalized loss

In [34]:
data_raw.iloc[82,1]= data_raw.iloc[81,1]
data_raw.iloc[83,1]= data_raw.iloc[81,1]
data_raw.iloc[84,1]= data_raw.iloc[81,1]

In [35]:
#CHECK MISSING VALUES FOR MAKE volkswagen

df14 = data_raw.loc[data_raw['make'] == 'volkswagen']
df14

symboling  normalized-losses        make fuel-type aspiration  \
182          2              122.0  volkswagen    diesel        std   
183          2              122.0  volkswagen       gas        std   
184          2               94.0  volkswagen    diesel        std   
185          2               94.0  volkswagen       gas        std   
186          2               94.0  volkswagen       gas        std   
187          2               94.0  volkswagen    diesel      turbo   
188          2               94.0  volkswagen       gas        std   
189          3                NaN  volkswagen       gas        std   
190          3              256.0  volkswagen       gas        std   
191          0                NaN  volkswagen       gas        std   
192          0                NaN  volkswagen    diesel      turbo   
193          0                NaN  volkswagen       gas        std   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  \
182          two        sedan          fwd           front        97.3   
183          two        sedan          fwd           front        97.3   
184         four        sedan          fwd           front        97.3   
185         four        sedan          fwd           front        97.3   
186         four        sedan          fwd           front        97.3   
187         four        sedan          fwd           front        97.3   
188         four        sedan          fwd           front        97.3   
189          two  convertible          fwd           front        94.5   
190          two    hatchback          fwd           front        94.5   
191         four        sedan          fwd           front       100.4   
192         four        sedan          fwd           front       100.4   
193         four        wagon          fwd           front       100.4   

     length  width  height  curb-weight engine-type num-of-cylinders  \
182   171.7   65.5    55.7         2261         ohc             four   
183   171.7   65.5    55.7         2209         ohc             four   
184   171.7   65.5    55.7         2264         ohc             four   
185   171.7   65.5    55.7         2212         ohc             four   
186   171.7   65.5    55.7         2275         ohc             four   
187   171.7   65.5    55.7         2319         ohc             four   
188   171.7   65.5    55.7         2300         ohc             four   
189   159.3   64.2    55.6         2254         ohc             four   
190   165.7   64.0    51.4         2221         ohc             four   
191   180.2   66.9    55.1         2661         ohc             five   
192   180.2   66.9    55.1         2579         ohc             four   
193   183.1   66.9    55.1         2563         ohc             four   

     engine-size fuel-system  bore  stroke  compression-ratio  horsepower  \
182           97         idi  3.01     3.4               23.0        52.0   
183          109        mpfi  3.19     3.4                9.0        85.0   
184           97         idi  3.01     3.4               23.0        52.0   
185          109        mpfi  3.19     3.4                9.0        85.0   
186          109        mpfi  3.19     3.4                9.0        85.0   
187           97         idi  3.01     3.4               23.0        68.0   
188          109        mpfi  3.19     3.4               10.0       100.0   
189          109        mpfi  3.19     3.4                8.5        90.0   
190          109        mpfi  3.19     3.4                8.5        90.0   
191          136        mpfi  3.19     3.4                8.5       110.0   
192           97         idi  3.01     3.4               23.0        68.0   
193          109        mpfi  3.19     3.4                9.0        88.0   

     peak-rpm  city-mpg  highway-mpg    price  normalized-losses_null  \
182    4800.0        37           46   7775.0                       0   
183    5250.0        27           34   7975.0 

the car with index number 188 is similar to index car 189. therfore we assume they have the same normalized losses

In [36]:
data_raw.iloc[189,1]= data_raw.iloc[188,1]

the car with index number 190 is similar to index cars 191, 192 and 193. 
therfore we assume they have the same normalized losses

In [37]:
data_raw.iloc[191,1]= data_raw.iloc[190,1]
data_raw.iloc[192,1]= data_raw.iloc[190,1]
data_raw.iloc[193,1]= data_raw.iloc[190,1]

In [38]:
#CHECK MISSING VALUES FOR MAKE peugot

df15 = data_raw.loc[data_raw['make'] == 'peugot']
df15

symboling  normalized-losses    make fuel-type aspiration num-of-doors  \
107          0              161.0  peugot       gas        std         four   
108          0              161.0  peugot    diesel      turbo         four   
109          0                NaN  peugot       gas        std         four   
110          0                NaN  peugot    diesel      turbo         four   
111          0              161.0  peugot       gas        std         four   
112          0              161.0  peugot    diesel      turbo         four   
113          0                NaN  peugot       gas        std         four   
114          0                NaN  peugot    diesel      turbo         four   
115          0              161.0  peugot       gas        std         four   
116          0              161.0  peugot    diesel      turbo         four   
117          0              161.0  peugot       gas      turbo         four   

    body-style drive-wheels engine-location  wheel-base  length  width  \
107      sedan          rwd           front       107.9   186.7   68.4   
108      sedan          rwd           front       107.9   186.7   68.4   
109      wagon          rwd           front       114.2   198.9   68.4   
110      wagon          rwd           front       114.2   198.9   68.4   
111      sedan          rwd           front       107.9   186.7   68.4   
112      sedan          rwd           front       107.9   186.7   68.4   
113      wagon          rwd           front       114.2   198.9   68.4   
114      wagon          rwd           front       114.2   198.9   68.4   
115      sedan          rwd           front       107.9   186.7   68.4   
116      sedan          rwd           front       107.9   186.7   68.4   
117      sedan          rwd           front       108.0   186.7   68.3   

     height  curb-weight engine-type num-of-cylinders  engine-size  \
107    56.7         3020           l             four          120   
108    56.7         3197           l             four          152   
109    58.7         3230           l             four          120   
110    58.7         3430           l             four          152   
111    56.7         3075           l             four          120   
112    56.7         3252           l             four          152   
113    56.7         3285           l             four          120   
114    58.7         3485           l             four          152   
115    56.7         3075           l             four          120   
116    56.7         3252           l             four          152   
117    56.0         3130           l             four          134   

    fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
107        mpfi  3.46    3.19                8.4        97.0    5000.0   
108         idi  3.70    3.52               21.0        95.0    4150.0   
109        mpfi  3.46    3.19                8.4        97.0    5000.0   
110         idi  3.70    3.52               21.0        95.0    4150.0   
111        mpfi  3.46    2.19                8.4        95.0    5000.0   
112         idi  3.70    3.52               21.0        95.0    4150.0   
113        mpfi  3.46    2.19                8.4        95.0    5000.0   
114         idi  3.70    3.52               21.0        95.0    4150.0   
115        mpfi  3.46    3.19                8.4        97.0    5000.0   
116         idi  3.70    3.52               21.0        95.0    4150.0   
117        mpfi  3.61    3.21                7.0       142.0    5600.0   

     city-mpg  highway-mpg    price  normalized-losses_null  \
107        19           24  11900.0                       0   
108        28           33  13200.0                       0   
109        19           24  12440.0                       1   
110        25           25  13860.0                       1   
111        19           24  15580.0                       0   
112        28           33  16900.0                       0

normalized losses is the same for all the cars of this brand

In [39]:
data_raw.iloc[109,1]= data_raw.iloc[108,1]
data_raw.iloc[110,1]= data_raw.iloc[108,1]
data_raw.iloc[113,1]= data_raw.iloc[108,1]
data_raw.iloc[114,1]= data_raw.iloc[108,1]

In [40]:
#CHECK MISSING VALUES FOR MAKE mercedes-benz

df16 = data_raw.loc[data_raw['make'] == 'mercedes-benz']
df16

symboling  normalized-losses           make fuel-type aspiration  \
67         -1               93.0  mercedes-benz    diesel      turbo   
68         -1               93.0  mercedes-benz    diesel      turbo   
69          0               93.0  mercedes-benz    diesel      turbo   
70         -1               93.0  mercedes-benz    diesel      turbo   
71         -1                NaN  mercedes-benz       gas        std   
72          3              142.0  mercedes-benz       gas        std   
73          0                NaN  mercedes-benz       gas        std   
74          1                NaN  mercedes-benz       gas        std   

   num-of-doors   body-style drive-wheels engine-location  wheel-base  length  \
67         four        sedan          rwd           front       110.0   190.9   
68         four        wagon          rwd           front       110.0   190.9   
69          two      hardtop          rwd           front       106.7   187.5   
70         four        sedan          rwd           front       115.6   202.6   
71         four        sedan          rwd           front       115.6   202.6   
72          two  convertible          rwd           front        96.6   180.3   
73         four        sedan          rwd           front       120.9   208.1   
74          two      hardtop          rwd           front       112.0   199.2   

    width  height  curb-weight engine-type num-of-cylinders  engine-size  \
67   70.3    56.5         3515         ohc             five          183   
68   70.3    58.7         3750         ohc             five          183   
69   70.3    54.9         3495         ohc             five          183   
70   71.7    56.3         3770         ohc             five          183   
71   71.7    56.5         3740        ohcv            eight          234   
72   70.5    50.8         3685        ohcv            eight          234   
73   71.7    56.7         3900        ohcv            eight          308   
74   72.0    55.4         3715        ohcv            eight          304   

   fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
67         idi  3.58    3.64               21.5       123.0    4350.0   
68         idi  3.58    3.64               21.5       123.0    4350.0   
69         idi  3.58    3.64               21.5       123.0    4350.0   
70         idi  3.58    3.64               21.5       123.0    4350.0   
71        mpfi  3.46    3.10                8.3       155.0    4750.0   
72        mpfi  3.46    3.10                8.3       155.0    4750.0   
73        mpfi  3.80    3.35                8.0       184.0    4500.0   
74        mpfi  3.80    3.35                8.0       184.0    4500.0   

    city-mpg  highway-mpg    price  normalized-losses_null  num-of-doors_null  \
67        22           25  25552.0                       0                  0   
68        22           25  28248.0                       0                  0   
69        22           25  28176.0                       0                  0   
70        22           25  31600.0                       0                  0   
71        16           18  34184.0                       1                  0   
72        16           18  35056.0                       0                  0   
73        14           16  40960.0                       1                  0   
74        14           16  45400.0                       1                  0   

    bore_null  stroke_null  horsepower_null  peak-rpm_null  price_null  
67          0            0                0              0           0  
68          0            0                0              0           0  
69          0            0                0              0           0  
70          0            0                0              0           0  
71          0            0                0              0           0  
72          0            0                0              0           0  
73          0            0               

the car with index number 70 is similar to index car 71. therfore we assume they have the same normalized losses
the car with index number 72 is similar to index cars 73 and 74. therfore we assume they have the same normalized losses

In [41]:
data_raw.iloc[71,1]= data_raw.iloc[70,1]
data_raw.iloc[73,1]= data_raw.iloc[72,1]
data_raw.iloc[74,1]= data_raw.iloc[72,1]

In [42]:
#CHECK MISSING VALUES FOR MAKE bmw

df17 = data_raw.loc[data_raw['make'] == 'bmw']
df17

symboling  normalized-losses make fuel-type aspiration num-of-doors  \
10          2              192.0  bmw       gas        std          two   
11          0              192.0  bmw       gas        std         four   
12          0              188.0  bmw       gas        std          two   
13          0              188.0  bmw       gas        std         four   
14          1                NaN  bmw       gas        std         four   
15          0                NaN  bmw       gas        std         four   
16          0                NaN  bmw       gas        std          two   
17          0                NaN  bmw       gas        std         four   

   body-style drive-wheels engine-location  wheel-base  length  width  height  \
10      sedan          rwd           front       101.2   176.8   64.8    54.3   
11      sedan          rwd           front       101.2   176.8   64.8    54.3   
12      sedan          rwd           front       101.2   176.8   64.8    54.3   
13      sedan          rwd           front       101.2   176.8   64.8    54.3   
14      sedan          rwd           front       103.5   189.0   66.9    55.7   
15      sedan          rwd           front       103.5   189.0   66.9    55.7   
16      sedan          rwd           front       103.5   193.8   67.9    53.7   
17      sedan          rwd           front       110.0   197.0   70.9    56.3   

    curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  \
10         2395         ohc             four          108        mpfi  3.50   
11         2395         ohc             four          108        mpfi  3.50   
12         2710         ohc              six          164        mpfi  3.31   
13         2765         ohc              six          164        mpfi  3.31   
14         3055         ohc              six          164        mpfi  3.31   
15         3230         ohc              six          209        mpfi  3.62   
16         3380         ohc              six          209        mpfi  3.62   
17         3505         ohc              six          209        mpfi  3.62   

    stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg  \
10    2.80                8.8       101.0    5800.0        23           29   
11    2.80                8.8       101.0    5800.0        23           29   
12    3.19                9.0       121.0    4250.0        21           28   
13    3.19                9.0       121.0    4250.0        21           28   
14    3.19                9.0       121.0    4250.0        20           25   
15    3.39                8.0       182.0    5400.0        16           22   
16    3.39                8.0       182.0    5400.0        16           22   
17    3.39                8.0       182.0    5400.0        15           20   

      price  normalized-losses_null  num-of-doors_null  bore_null  \
10  16430.0                       0                  0          0   
11  16925.0                       0                  0          0   
12  20970.0                       0                  0          0   
13  21105.0                       0                  0          0   
14  24565.0                       1                  0          0   
15  30760.0                       1                  0          0   
16  41315.0                       1                  0          0   
17  36880.0                       1                  0          0   

    stroke_null  horsepower_null  peak-rpm_null  price_null  
10            0                0              0           0  
11            0                0              0           0  
12            0                0              0           0  
13            0                0              0           0  
14            0                0              0           0  
15            0                0              0           0  
16            0                0              0           0  
17            0                0              0           0

In [43]:
data_raw.iloc[14,1]= data_raw.iloc[11,1]
data_raw.iloc[15,1]= data_raw.iloc[11,1]
data_raw.iloc[16,1]= data_raw.iloc[11,1]
data_raw.iloc[17,1]= data_raw.iloc[11,1]

In [44]:
#CHECK MISSING VALUES FOR MAKE audi

df18 = data_raw.loc[data_raw['make'] == 'audi']
df18

symboling  normalized-losses  make fuel-type aspiration num-of-doors  \
3          2              164.0  audi       gas        std         four   
4          2              164.0  audi       gas        std         four   
5          2                NaN  audi       gas        std          two   
6          1              158.0  audi       gas        std         four   
7          1                NaN  audi       gas        std         four   
8          1              158.0  audi       gas      turbo         four   
9          0                NaN  audi       gas      turbo          two   

  body-style drive-wheels engine-location  wheel-base  length  width  height  \
3      sedan          fwd           front        99.8   176.6   66.2    54.3   
4      sedan          4wd           front        99.4   176.6   66.4    54.3   
5      sedan          fwd           front        99.8   177.3   66.3    53.1   
6      sedan          fwd           front       105.8   192.7   71.4    55.7   
7      wagon          fwd           front       105.8   192.7   71.4    55.7   
8      sedan          fwd           front       105.8   192.7   71.4    55.9   
9  hatchback          4wd           front        99.5   178.2   67.9    52.0   

   curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  \
3         2337         ohc             four          109        mpfi  3.19   
4         2824         ohc             five          136        mpfi  3.19   
5         2507         ohc             five          136        mpfi  3.19   
6         2844         ohc             five          136        mpfi  3.19   
7         2954         ohc             five          136        mpfi  3.19   
8         3086         ohc             five          131        mpfi  3.13   
9         3053         ohc             five          131        mpfi  3.13   

   stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg  \
3     3.4               10.0       102.0    5500.0        24           30   
4     3.4                8.0       115.0    5500.0        18           22   
5     3.4                8.5       110.0    5500.0        19           25   
6     3.4                8.5       110.0    5500.0        19           25   
7     3.4                8.5       110.0    5500.0        19           25   
8     3.4                8.3       140.0    5500.0        17           20   
9     3.4                7.0       160.0    5500.0        16           22   

     price  normalized-losses_null  num-of-doors_null  bore_null  stroke_null  \
3  13950.0                       0                  0          0            0   
4  17450.0                       0                  0          0            0   
5  15250.0                       1                  0          0            0   
6  17710.0                       0                  0          0            0   
7  18920.0                       1                  0          0            0   
8  23875.0                       0                  0          0            0   
9      NaN                       1                  0          0            0   

   horsepower_null  peak-rpm_null  price_null  
3                0              0           0  
4                0              0           0  
5                0              0           0  
6                0              0           0  
7                0              0           0  
8                0              0           0  
9                0              0           1

In [45]:
data_raw.iloc[5,1]= data_raw.iloc[4,1]
data_raw.iloc[7,1]= data_raw.iloc[8,1]
data_raw.iloc[9,1]= data_raw.iloc[8,1]
data_raw.iloc[9,25]= data_raw.iloc[8,25]

In [46]:
#CHECK MISSING VALUES FOR MAKE plymouth

df19 = data_raw.loc[data_raw['make'] == 'plymouth']
df19

symboling  normalized-losses      make fuel-type aspiration num-of-doors  \
118          1              119.0  plymouth       gas        std          two   
119          1              119.0  plymouth       gas      turbo          two   
120          1              154.0  plymouth       gas        std         four   
121          1              154.0  plymouth       gas        std         four   
122          1              154.0  plymouth       gas        std         four   
123         -1               74.0  plymouth       gas        std         four   
124          3                NaN  plymouth       gas      turbo          two   

    body-style drive-wheels engine-location  wheel-base  length  width  \
118  hatchback          fwd           front        93.7   157.3   63.8   
119  hatchback          fwd           front        93.7   157.3   63.8   
120  hatchback          fwd           front        93.7   157.3   63.8   
121      sedan          fwd           front        93.7   167.3   63.8   
122      sedan          fwd           front        93.7   167.3   63.8   
123      wagon          fwd           front       103.3   174.6   64.6   
124  hatchback          rwd           front        95.9   173.2   66.3   

     height  curb-weight engine-type num-of-cylinders  engine-size  \
118    50.8         1918         ohc             four           90   
119    50.8         2128         ohc             four           98   
120    50.6         1967         ohc             four           90   
121    50.8         1989         ohc             four           90   
122    50.8         2191         ohc             four           98   
123    59.8         2535         ohc             four          122   
124    50.2         2818         ohc             four          156   

    fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
118        2bbl  2.97    3.23                9.4        68.0    5500.0   
119        spdi  3.03    3.39                7.6       102.0    5500.0   
120        2bbl  2.97    3.23                9.4        68.0    5500.0   
121        2bbl  2.97    3.23                9.4        68.0    5500.0   
122        2bbl  2.97    3.23                9.4        68.0    5500.0   
123        2bbl  3.35    3.46                8.5        88.0    5000.0   
124        spdi  3.59    3.86                7.0       145.0    5000.0   

     city-mpg  highway-mpg    price  normalized-losses_null  \
118        37           41   5572.0                       0   
119        24           30   7957.0                       0   
120        31           38   6229.0                       0   
121        31           38   6692.0                       0   
122        31           38   7609.0                       0   
123        24           30   8921.0                       0   
124        19           24  12764.0                       1   

     num-of-doors_null  bore_null  stroke_null  horsepower_null  \
118                  0          0            0                0   
119                  0          0            0                0   
120                  0          0            0                0   
121                  0          0            0                0   
122                  0          0            0                0   
123                  0          0            0                0   
124                  0          0            0                0   

     peak-rpm_null  price_null  
118              0           0  
119              0           0  
120              0           0  
121              0           0  
122              0           0  
123              0           0  
124              0           0

In [47]:
data_raw.iloc[124,1]= data_raw.iloc[119,1]

In [48]:
#CHECK MISSING VALUES FOR MAKE porsche

df20 = data_raw.loc[data_raw['make'] == 'porsche']
df20

symboling  normalized-losses     make fuel-type aspiration num-of-doors  \
125          3              186.0  porsche       gas        std          two   
126          3                NaN  porsche       gas        std          two   
127          3                NaN  porsche       gas        std          two   
128          3                NaN  porsche       gas        std          two   
129          1                NaN  porsche       gas        std          two   

      body-style drive-wheels engine-location  wheel-base  length  width  \
125    hatchback          rwd           front        94.5   168.9   68.3   
126      hardtop          rwd            rear        89.5   168.9   65.0   
127      hardtop          rwd            rear        89.5   168.9   65.0   
128  convertible          rwd            rear        89.5   168.9   65.0   
129    hatchback          rwd           front        98.4   175.7   72.3   

     height  curb-weight engine-type num-of-cylinders  engine-size  \
125    50.2         2778         ohc             four          151   
126    51.6         2756        ohcf              six          194   
127    51.6         2756        ohcf              six          194   
128    51.6         2800        ohcf              six          194   
129    50.5         3366       dohcv            eight          203   

    fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
125        mpfi  3.94    3.11                9.5       143.0    5500.0   
126        mpfi  3.74    2.90                9.5       207.0    5900.0   
127        mpfi  3.74    2.90                9.5       207.0    5900.0   
128        mpfi  3.74    2.90                9.5       207.0    5900.0   
129        mpfi  3.94    3.11               10.0       288.0    5750.0   

     city-mpg  highway-mpg    price  normalized-losses_null  \
125        19           27  22018.0                       0   
126        17           25  32528.0                       1   
127        17           25  34028.0                       1   
128        17           25  37028.0                       1   
129        17           28      NaN                       1   

     num-of-doors_null  bore_null  stroke_null  horsepower_null  \
125                  0          0            0                0   
126                  0          0            0                0   
127                  0          0            0                0   
128                  0          0            0                0   
129                  0          0            0                0   

     peak-rpm_null  price_null  
125              0           0  
126              0           0  
127              0           0  
128              0           0  
129              0           1

In [49]:
data_raw.iloc[126,1]= data_raw.iloc[125,1]
data_raw.iloc[127,1]= data_raw.iloc[125,1]
data_raw.iloc[128,1]= data_raw.iloc[125,1]
data_raw.iloc[129,1]= data_raw.iloc[125,1]

In [50]:
data_raw.iloc[129,25]= data_raw.iloc[128,25]

In [51]:
#CHECK MISSING VALUES FOR MAKE isuzu

df21 = data_raw.loc[data_raw['make'] == 'isuzu']
df21

symboling  normalized-losses   make fuel-type aspiration num-of-doors  \
43          0                NaN  isuzu       gas        std         four   
44          1                NaN  isuzu       gas        std          two   
45          0                NaN  isuzu       gas        std         four   
46          2                NaN  isuzu       gas        std          two   

   body-style drive-wheels engine-location  wheel-base  length  width  height  \
43      sedan          rwd           front        94.3   170.7   61.8    53.5   
44      sedan          fwd           front        94.5   155.9   63.6    52.0   
45      sedan          fwd           front        94.5   155.9   63.6    52.0   
46  hatchback          rwd           front        96.0   172.6   65.2    51.4   

    curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  \
43         2337         ohc             four          111        2bbl  3.31   
44         1874         ohc             four           90        2bbl  3.03   
45         1909         ohc             four           90        2bbl  3.03   
46         2734         ohc             four          119        spfi  3.43   

    stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg  \
43    3.23                8.5        78.0    4800.0        24           29   
44    3.11                9.6        70.0    5400.0        38           43   
45    3.11                9.6        70.0    5400.0        38           43   
46    3.23                9.2        90.0    5000.0        24           29   

      price  normalized-losses_null  num-of-doors_null  bore_null  \
43   6785.0                       1                  0          0   
44      NaN                       1                  0          0   
45      NaN                       1                  0          0   
46  11048.0                       1                  0          0   

    stroke_null  horsepower_null  peak-rpm_null  price_null  
43            0                0              0           0  
44            0                0              0           1  
45            0                0              0           1  
46            0                0              0           0

In [52]:
#price proporcional to the horsepower, then the price for 9.6 is:
p = 6785*9.6/8.5
p

7663.058823529412

In [53]:
data_raw.iloc[44,25]= p
data_raw.iloc[45,25]= p

In [54]:
nl = data_raw['normalized-losses'].mean()

In [55]:
data_raw.iloc[43,1] = nl
data_raw.iloc[44,1] = nl
data_raw.iloc[45,1] = nl
data_raw.iloc[46,1] = nl

In [56]:
#CHECK MISSING VALUES FOR MAKE jaguar

df22 = data_raw.loc[data_raw['make'] == 'jaguar']
df22

symboling  normalized-losses    make fuel-type aspiration num-of-doors  \
47          0              145.0  jaguar       gas        std         four   
48          0                NaN  jaguar       gas        std         four   
49          0                NaN  jaguar       gas        std          two   

   body-style drive-wheels engine-location  wheel-base  length  width  height  \
47      sedan          rwd           front       113.0   199.6   69.6    52.8   
48      sedan          rwd           front       113.0   199.6   69.6    52.8   
49      sedan          rwd           front       102.0   191.7   70.6    47.8   

    curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  \
47         4066        dohc              six          258        mpfi  3.63   
48         4066        dohc              six          258        mpfi  3.63   
49         3950        ohcv           twelve          326        mpfi  3.54   

    stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg  \
47    4.17                8.1       176.0    4750.0        15           19   
48    4.17                8.1       176.0    4750.0        15           19   
49    2.76               11.5       262.0    5000.0        13           17   

      price  normalized-losses_null  num-of-doors_null  bore_null  \
47  32250.0                       0                  0          0   
48  35550.0                       1                  0          0   
49  36000.0                       1                  0          0   

    stroke_null  horsepower_null  peak-rpm_null  price_null  
47            0                0              0           0  
48            0                0              0           0  
49            0                0              0           0

In [57]:
data_raw.iloc[48,1]= data_raw.iloc[47,1]
data_raw.iloc[49,1]= data_raw.iloc[47,1]

In [58]:
#CHECK MISSING VALUES FOR MAKE alfa-romero

df23 = data_raw.loc[data_raw['make'] == 'alfa-romero']
df23

symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std   
1          3                NaN  alfa-romero       gas        std   
2          1                NaN  alfa-romero       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  length  \
0          two  convertible          rwd           front        88.6   168.8   
1          two  convertible          rwd           front        88.6   168.8   
2          two    hatchback          rwd           front        94.5   171.2   

   width  height  curb-weight engine-type num-of-cylinders  engine-size  \
0   64.1    48.8         2548        dohc             four          130   
1   64.1    48.8         2548        dohc             four          130   
2   65.5    52.4         2823        ohcv              six          152   

  fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
0        mpfi  3.47    2.68                9.0       111.0    5000.0   
1        mpfi  3.47    2.68                9.0       111.0    5000.0   
2        mpfi  2.68    3.47                9.0       154.0    5000.0   

   city-mpg  highway-mpg    price  normalized-losses_null  num-of-doors_null  \
0        21           27  13495.0                       1                  0   
1        21           27  16500.0                       1                  0   
2        19           26  16500.0                       1                  0   

   bore_null  stroke_null  horsepower_null  peak-rpm_null  price_null  
0          0            0                0              0           0  
1          0            0                0              0           0  
2          0            0                0              0           0

In [59]:
data_raw.iloc[0,1]= nl
data_raw.iloc[1,1]= nl
data_raw.iloc[2,1]= nl

In [60]:
#CHECK MISSING VALUES FOR MAKE renault

df24 = data_raw.loc[data_raw['make'] == 'renault']
df24

symboling  normalized-losses     make fuel-type aspiration num-of-doors  \
130          0                NaN  renault       gas        std         four   
131          2                NaN  renault       gas        std          two   

    body-style drive-wheels engine-location  wheel-base  length  width  \
130      wagon          fwd           front        96.1   181.5   66.5   
131  hatchback          fwd           front        96.1   176.8   66.6   

     height  curb-weight engine-type num-of-cylinders  engine-size  \
130    55.2         2579         ohc             four          132   
131    50.5         2460         ohc             four          132   

    fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
130        mpfi  3.46     3.9                8.7         NaN       NaN   
131        mpfi  3.46     3.9                8.7         NaN       NaN   

     city-mpg  highway-mpg   price  normalized-losses_null  num-of-doors_null  \
130        23           31  9295.0                       1                  0   
131        23           31  9895.0                       1                  0   

     bore_null  stroke_null  horsepower_null  peak-rpm_null  price_null  
130          0            0                1              1           0  
131          0            0                1              1           0

In [61]:
data_raw.iloc[130,1]= nl
data_raw.iloc[131,1]= nl


In [62]:
# engine size proportianl to horsepower. Using mercury data
hp = 175*132/140

In [63]:
data_raw.iloc[130,21]= hp
data_raw.iloc[131,21]= hp

In [64]:
prpm = data_raw['peak-rpm'].mean()

In [65]:
data_raw.iloc[130,22]= prpm
data_raw.iloc[131,22]= prpm

In [66]:
#CHECK MISSING VALUES FOR MAKE mercury

df25 = data_raw.loc[data_raw['make'] == 'mercury']
df25

symboling  normalized-losses     make fuel-type aspiration num-of-doors  \
75          1                NaN  mercury       gas      turbo          two   

   body-style drive-wheels engine-location  wheel-base  length  width  height  \
75  hatchback          rwd           front       102.7   178.4   68.0    54.8   

    curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  \
75         2910         ohc             four          140        mpfi  3.78   

    stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg  \
75    3.12                8.0       175.0    5000.0        19           24   

      price  normalized-losses_null  num-of-doors_null  bore_null  \
75  16503.0                       1                  0          0   

    stroke_null  horsepower_null  peak-rpm_null  price_null  
75            0                0              0           0

In [67]:
data_raw.iloc[75,1]= nl

In [68]:
data_clean = data_raw.copy()

In [69]:
data_clean.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price', 'normalized-losses_null', 'num-of-doors_null',
       'bore_null', 'stroke_null', 'horsepower_null', 'peak-rpm_null',
       'price_null'],
      dtype='object')

DROPPING NULL COLUMNS

In [70]:
data_clean = data_clean.drop(['normalized-losses_null', 'num-of-doors_null',
       'bore_null', 'stroke_null', 'horsepower_null', 'peak-rpm_null',
       'price_null'], axis = 1)

In [71]:
#MAKING SURE THERE ARE NOT MISSING VALUES

In [72]:
data_clean.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

CREATING A FILE WITH THE DATAFRAME WITHOUT MISSING VALUES

In [73]:
data_clean.to_csv('C:\\Users\\gusal\\machine learning\\Feature engineering\\automobile data set\\imports-85-clean-data.csv')